# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #env:
    #  REQUIRED_LIBRARIES: Servo,Adafruit NeoPixel

    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:nano
          - arduino:avr:uno
          - esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
        include:
          - arduino-boards-fqbn: arduino:avr:nano

          - arduino-boards-fqbn: arduino:avr:uno

          - arduino-boards-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
            platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Test compile for Arduino
      uses: ArminJo/arduino-test-compile@v2.2.0
      with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
